/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dae.gui.fuzzy;

import dae.gui.fuzzy.dialog.CreateLeftSigmoidDialog;
import dae.gui.fuzzy.dialog.CreateRightSigmoidDialog;
import dae.gui.fuzzy.dialog.CreateSigmoidDialog;
import dae.gui.fuzzy.dialog.CreateSingletonDialog;
import dae.gui.fuzzy.dialog.CreateTrapezoidDialog;
import dae.gui.fuzzy.model.FuzzyOutputListModel;
import java.awt.Frame;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import mlproject.fuzzy.FuzzySystem;
import mlproject.fuzzy.FuzzyVariable;
import mlproject.fuzzy.MemberShip;
import mlproject.fuzzy.SingletonMemberShip;

/**
 *
 * @author Koen Samyn
 */
public class FuzzyOutputVariablePanel extends javax.swing.JPanel implements ItemListener {
    private FuzzySystem fuzzySystem;
    private FuzzyOutputListModel fuzzyOutputListModel;
    
    private CreateLeftSigmoidDialog leftSigmoidDialog;
    private CreateRightSigmoidDialog rightSigmoidDialog;
    private CreateSigmoidDialog sigmoidDialog;
    private CreateTrapezoidDialog trapezoidDialog;
    private CreateSingletonDialog singletonDialog;
    /**
     * Creates new form FuzzyInputVariablePanel
     */
    public FuzzyOutputVariablePanel() {
        initComponents();
        
        leftSigmoidDialog = new CreateLeftSigmoidDialog((Frame)this.getTopLevelAncestor(), true);
        rightSigmoidDialog = new CreateRightSigmoidDialog((Frame)this.getTopLevelAncestor(), true);
        sigmoidDialog = new CreateSigmoidDialog((Frame)this.getTopLevelAncestor(), true);
        trapezoidDialog = new CreateTrapezoidDialog((Frame)this.getTopLevelAncestor(),true);
        singletonDialog = new CreateSingletonDialog((Frame)this.getTopLevelAncestor(),true);
    }
    
    public void setFuzzySystem(FuzzySystem fuzzySystem){
        this.fuzzySystem = fuzzySystem;
        fuzzyOutputListModel = new FuzzyOutputListModel(fuzzySystem);
        lstFuzzyVariables.setModel(fuzzyOutputListModel);
        
        fuzzyVariableGUI1.addItemListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        scrVariableList = new javax.swing.JScrollPane();
        lstFuzzyVariables = new javax.swing.JList();
        fuzzyVariableGUI1 = new mlproject.fuzzy.gui.FuzzyVariableGUI();
        btnAddFuzzyVariable = new javax.swing.JButton();
        btnDeleteVariable = new javax.swing.JButton();
        memberShipEditorPanel1 = new dae.gui.fuzzy.MemberShipEditorPanel();
        btnAddMembership = new javax.swing.JButton();
        btnRemoveMembership = new javax.swing.JButton();
        cboMembershipType = new javax.swing.JComboBox();

        jButton1.setText("jButton1");

        setPreferredSize(new java.awt.Dimension(800, 320));

        lstFuzzyVariables.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstFuzzyVariables.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstFuzzyVariablesValueChanged(evt);
            }
        });
        scrVariableList.setViewportView(lstFuzzyVariables);

        fuzzyVariableGUI1.setPreferredSize(new java.awt.Dimension(300, 100));

        btnAddFuzzyVariable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dae/icons/add.png"))); // NOI18N
        btnAddFuzzyVariable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFuzzyVariableActionPerformed(evt);
            }
        });

        btnDeleteVariable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dae/icons/delete.png"))); // NOI18N

        memberShipEditorPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Membership Editor"));

        btnAddMembership.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dae/icons/add.png"))); // NOI18N
        btnAddMembership.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMembershipActionPerformed(evt);
            }
        });

        btnRemoveMembership.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dae/icons/delete.png"))); // NOI18N
        btnRemoveMembership.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveMembershipActionPerformed(evt);
            }
        });

        cboMembershipType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Singleton" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrVariableList, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fuzzyVariableGUI1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDeleteVariable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddFuzzyVariable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemoveMembership)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboMembershipType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddMembership)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(memberShipEditorPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(btnAddFuzzyVariable))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(btnDeleteVariable))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(memberShipEditorPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(scrVariableList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                    .addComponent(fuzzyVariableGUI1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(btnRemoveMembership)
                                    .addComponent(cboMembershipType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddMembership))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lstFuzzyVariablesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstFuzzyVariablesValueChanged
        // TODO add your handling code here:
        
        FuzzyVariable selected = (FuzzyVariable)lstFuzzyVariables.getSelectedValue();
        if ( selected != null){
            fuzzyVariableGUI1.setFuzzyVariable(selected);
        }
    }//GEN-LAST:event_lstFuzzyVariablesValueChanged

    private void btnAddFuzzyVariableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFuzzyVariableActionPerformed
        // TODO add your handling code here:
        String name = "output";
        int index =1;
        while ( fuzzySystem.hasFuzzyOutputVariable(name+index )){
            ++index;
        }
        FuzzyVariable fv = new FuzzyVariable(name+index);
        fv.addMemberShip(new SingletonMemberShip( "leftfast", -5));
        fv.addMemberShip(new SingletonMemberShip( "left", -2.5f));
        fv.addMemberShip(new SingletonMemberShip( "stay", 0));
        fv.addMemberShip(new SingletonMemberShip( "right", 2.5f));
        fv.addMemberShip(new SingletonMemberShip( "rightfast", 5));
        
        fuzzyOutputListModel.addFuzzyVariable(fv);
    }//GEN-LAST:event_btnAddFuzzyVariableActionPerformed

    private void btnAddMembershipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMembershipActionPerformed
        // TODO add your handling code here:
       // String memberShipName = JOptionPane.show(this, "Name for this membership function : ");
        if (cboMembershipType.getSelectedItem().equals("Left")){
            leftSigmoidDialog.setLocationRelativeTo(this);
            leftSigmoidDialog.setVisible(true);
            if ( leftSigmoidDialog.getReturnStatus() == leftSigmoidDialog.RET_OK)
            {
                fuzzyVariableGUI1.addMemberShip(leftSigmoidDialog.getResult());
            }
        }else if (cboMembershipType.getSelectedItem().equals("Right")){
            rightSigmoidDialog.setLocationRelativeTo(this);
            rightSigmoidDialog.setVisible(true);
            if ( rightSigmoidDialog.getReturnStatus() == rightSigmoidDialog.RET_OK)
            {
                fuzzyVariableGUI1.addMemberShip(rightSigmoidDialog.getResult());
            }
        }else if (cboMembershipType.getSelectedItem().equals("Triangular")){
            sigmoidDialog.setLocationRelativeTo(this);
            sigmoidDialog.setVisible(true);
            if ( sigmoidDialog.getReturnStatus() == sigmoidDialog.RET_OK)
            {
                fuzzyVariableGUI1.addMemberShip(sigmoidDialog.getResult());
            }
        }else if (cboMembershipType.getSelectedItem().equals("Trapezoid")){
            trapezoidDialog.setLocationRelativeTo(this);
            trapezoidDialog.setVisible(true);
            if ( trapezoidDialog.getReturnStatus() == trapezoidDialog.RET_OK)
            {
                fuzzyVariableGUI1.addMemberShip(trapezoidDialog.getResult());
            }
        }else if (cboMembershipType.getSelectedItem().equals("Singleton")){
            singletonDialog.setLocationRelativeTo(this);
            singletonDialog.setVisible(true);
            if ( singletonDialog.getReturnStatus() == trapezoidDialog.RET_OK)
            {
                fuzzyVariableGUI1.addMemberShip(singletonDialog.getResult());
            }
        }
    }//GEN-LAST:event_btnAddMembershipActionPerformed

    private void btnRemoveMembershipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveMembershipActionPerformed
        // TODO add your handling code here:
        fuzzyVariableGUI1.deleteSelection();
    }//GEN-LAST:event_btnRemoveMembershipActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFuzzyVariable;
    private javax.swing.JButton btnAddMembership;
    private javax.swing.JButton btnDeleteVariable;
    private javax.swing.JButton btnRemoveMembership;
    private javax.swing.JComboBox cboMembershipType;
    private mlproject.fuzzy.gui.FuzzyVariableGUI fuzzyVariableGUI1;
    private javax.swing.JButton jButton1;
    private javax.swing.JList lstFuzzyVariables;
    private dae.gui.fuzzy.MemberShipEditorPanel memberShipEditorPanel1;
    private javax.swing.JScrollPane scrVariableList;
    // End of variables declaration//GEN-END:variables

    public void itemStateChanged(ItemEvent e) {
       memberShipEditorPanel1.setMemberShip((MemberShip)e.getItem());
    }
}
