/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dae.gui.fuzzy;

import dae.gui.fuzzy.model.FuzzyInputListModel;
import mlproject.fuzzy.FuzzySystem;
import mlproject.fuzzy.FuzzyVariable;
import mlproject.fuzzy.LeftSigmoidMemberShip;
import mlproject.fuzzy.RightSigmoidMemberShip;
import mlproject.fuzzy.SigmoidMemberShip;

/**
 *
 * @author Koen Samyn
 */
public class FuzzyInputVariablePanel extends javax.swing.JPanel {
    private FuzzySystem fuzzySystem;
    private FuzzyInputListModel fuzzyInputListModel;
    /**
     * Creates new form FuzzyInputVariablePanel
     */
    public FuzzyInputVariablePanel() {
        initComponents();
    }
    
    public void setFuzzySystem(FuzzySystem fuzzySystem){
        this.fuzzySystem = fuzzySystem;
        fuzzyInputListModel = new FuzzyInputListModel(fuzzySystem);
        lstFuzzyVariables.setModel(fuzzyInputListModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstFuzzyVariables = new javax.swing.JList();
        fuzzyVariableGUI1 = new mlproject.fuzzy.gui.FuzzyVariableGUI();
        btnAddFuzzyVariable = new javax.swing.JButton();
        btnDeleteVariable = new javax.swing.JButton();

        jButton1.setText("jButton1");

        lstFuzzyVariables.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstFuzzyVariables.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstFuzzyVariablesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstFuzzyVariables);

        btnAddFuzzyVariable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dae/icons/add.png"))); // NOI18N
        btnAddFuzzyVariable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFuzzyVariableActionPerformed(evt);
            }
        });

        btnDeleteVariable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dae/icons/delete.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDeleteVariable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddFuzzyVariable)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fuzzyVariableGUI1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fuzzyVariableGUI1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddFuzzyVariable)
                            .addComponent(btnDeleteVariable))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lstFuzzyVariablesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstFuzzyVariablesValueChanged
        // TODO add your handling code here:
        
        FuzzyVariable selected = (FuzzyVariable)lstFuzzyVariables.getSelectedValue();
        if ( selected != null){
            fuzzyVariableGUI1.setFuzzyVariable(selected);
        }
    }//GEN-LAST:event_lstFuzzyVariablesValueChanged

    private void btnAddFuzzyVariableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFuzzyVariableActionPerformed
        // TODO add your handling code here:
        String name = "input";
        int index =1;
        while ( fuzzySystem.hasFuzzyInputVariable(name+index )){
            ++index;
        }
        FuzzyVariable fv = new FuzzyVariable(name+index);
        fv.addMemberShip(new LeftSigmoidMemberShip(-15, -5, "FARLEFT"));
        fv.addMemberShip(new SigmoidMemberShip(-15.0f, -5, 0, "LEFT"));
        fv.addMemberShip(new SigmoidMemberShip(-5, 0, 5, "CENTER"));
        fv.addMemberShip(new SigmoidMemberShip(0, 5, 15, "RIGHT"));
        fv.addMemberShip(new RightSigmoidMemberShip(5, 15, "FARRIGHT"));
        
        fuzzyInputListModel.addFuzzyVariable(fv);
    }//GEN-LAST:event_btnAddFuzzyVariableActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFuzzyVariable;
    private javax.swing.JButton btnDeleteVariable;
    private mlproject.fuzzy.gui.FuzzyVariableGUI fuzzyVariableGUI1;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstFuzzyVariables;
    // End of variables declaration//GEN-END:variables
}
