/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dae.gui.fuzzy;

import java.awt.CardLayout;
import javax.swing.SwingUtilities;
import mlproject.fuzzy.LeftSigmoidMemberShip;
import mlproject.fuzzy.MemberShip;
import mlproject.fuzzy.RightSigmoidMemberShip;
import mlproject.fuzzy.SigmoidMemberShip;
import mlproject.fuzzy.SingletonMemberShip;
import mlproject.fuzzy.TrapezoidMemberShip;

/**
 *
 * @author Koen Samyn
 */
public class MemberShipEditorPanel extends javax.swing.JPanel {

    /**
     * Creates new form MemberShipEditorPanel
     */
    public MemberShipEditorPanel() {
        initComponents();
        SwingUtilities.updateComponentTreeUI(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftSigmoidPanel1 = new dae.gui.fuzzy.LeftSigmoidPanel();
        sigmoidPanel1 = new dae.gui.fuzzy.SigmoidPanel();
        rightSigmoidPanel1 = new dae.gui.fuzzy.RightSigmoidPanel();
        trapezoidSigmoidPanel1 = new dae.gui.fuzzy.TrapezoidSigmoidPanel();
        singletonPanel1 = new dae.gui.fuzzy.SingletonPanel();

        setLayout(new java.awt.CardLayout());
        add(leftSigmoidPanel1, "leftsigmoid");
        add(sigmoidPanel1, "sigmoid");
        add(rightSigmoidPanel1, "rightsigmoid");
        add(trapezoidSigmoidPanel1, "trapezoidsigmoid");
        add(singletonPanel1, "singleton");
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private dae.gui.fuzzy.LeftSigmoidPanel leftSigmoidPanel1;
    private dae.gui.fuzzy.RightSigmoidPanel rightSigmoidPanel1;
    private dae.gui.fuzzy.SigmoidPanel sigmoidPanel1;
    private dae.gui.fuzzy.SingletonPanel singletonPanel1;
    private dae.gui.fuzzy.TrapezoidSigmoidPanel trapezoidSigmoidPanel1;
    // End of variables declaration//GEN-END:variables

    public void setMemberShip(MemberShip memberShip) {
        if ( memberShip instanceof LeftSigmoidMemberShip){
            leftSigmoidPanel1.setMemberShip((LeftSigmoidMemberShip)memberShip);
            CardLayout cl = (CardLayout)this.getLayout();
            cl.show(this, "leftsigmoid");
        }else if ( memberShip instanceof SigmoidMemberShip){
            sigmoidPanel1.setMemberShip((SigmoidMemberShip)memberShip);
            CardLayout cl = (CardLayout)this.getLayout();
            cl.show(this, "sigmoid");
        }else if ( memberShip instanceof RightSigmoidMemberShip){
            rightSigmoidPanel1.setMemberShip((RightSigmoidMemberShip)memberShip);
            CardLayout cl = (CardLayout)this.getLayout();
            cl.show(this, "rightsigmoid");
        }else if ( memberShip instanceof TrapezoidMemberShip){
            trapezoidSigmoidPanel1.setMemberShip((TrapezoidMemberShip)memberShip);
            CardLayout cl = (CardLayout)this.getLayout();
            cl.show(this, "trapezoidsigmoid");
        }else if ( memberShip instanceof SingletonMemberShip){
            singletonPanel1.setMemberShip((SingletonMemberShip)memberShip);
            CardLayout cl = (CardLayout)this.getLayout();
            cl.show(this, "singleton");
        }
    }
}
