/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dae.gui.fuzzy;

import java.awt.Color;
import javax.swing.UIManager;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import mlproject.fuzzy.RightSigmoidMemberShip;

/**
 *
 * @author Koen Samyn
 */
public class RightSigmoidPanel extends javax.swing.JPanel implements DocumentListener{

    private RightSigmoidMemberShip membership;
    private Color errorColor;
    private Color normalColor;

    /**
     * Creates new form LeftSigmoidPanel
     */
    public RightSigmoidPanel() {
        initComponents();
        txtMembershipName.getDocument().addDocumentListener(this);
        errorColor = UIManager.getDefaults().getColor("nimbusRed");
        if (errorColor == null) {
            errorColor = Color.RED;
        }
        normalColor = UIManager.getDefaults().getColor("text");
        if (normalColor == null) {
            normalColor = Color.BLACK;
        }
    }

    public void setMemberShip(RightSigmoidMemberShip memberShip) {
        this.membership = memberShip;
        txtMembershipName.setText(memberShip.getName());
        spnLeft.setValue(memberShip.getLeft());
        spnCenter.setValue(memberShip.getCenter());
    }

    public void insertUpdate(DocumentEvent e) {
        updateMemberShipName();
    }

    public void removeUpdate(DocumentEvent e) {
        updateMemberShipName();
    }

    public void changedUpdate(DocumentEvent e) {
        updateMemberShipName();
    }

    private void updateMemberShipName() {
        String newName = txtMembershipName.getText();
        this.membership.setName(newName);

        if (!membership.getName().equals(newName)) {
            txtMembershipName.setForeground(errorColor);
        } else {
            txtMembershipName.setForeground(normalColor);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        txtMembershipName = new javax.swing.JTextField();
        lblLeft = new javax.swing.JLabel();
        spnLeft = new javax.swing.JSpinner();
        lblCenter = new javax.swing.JLabel();
        spnCenter = new javax.swing.JSpinner();

        lblName.setText("Membership name :");

        lblLeft.setText("Left :");

        spnLeft.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), null, null, Float.valueOf(0.1f)));
        spnLeft.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnLeftStateChanged(evt);
            }
        });

        lblCenter.setText("Center :");

        spnCenter.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), null, null, Float.valueOf(0.1f)));
        spnCenter.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnCenterStateChanged(evt);
            }
        });

        lblName.putClientProperty("JComponent.sizeVariant", "small");
        txtMembershipName.putClientProperty("JComponent.sizeVariant", "small");
        lblLeft.putClientProperty("JComponent.sizeVariant", "small");
        spnLeft.putClientProperty("JComponent.sizeVariant", "small");
        lblCenter.putClientProperty("JComponent.sizeVariant", "small");
        spnCenter.putClientProperty("JComponent.sizeVariant", "small");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName)
                    .addComponent(lblLeft)
                    .addComponent(lblCenter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMembershipName, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                    .addComponent(spnLeft)
                    .addComponent(spnCenter))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtMembershipName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLeft)
                    .addComponent(spnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCenter)
                    .addComponent(spnCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void spnLeftStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnLeftStateChanged
        // TODO add your handling code here:
        membership.setLeft((Float) spnLeft.getValue());
    }//GEN-LAST:event_spnLeftStateChanged

    private void spnCenterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnCenterStateChanged
        // TODO add your handling code here:
        membership.setCenter((Float) spnCenter.getValue());
    }//GEN-LAST:event_spnCenterStateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCenter;
    private javax.swing.JLabel lblLeft;
    private javax.swing.JLabel lblName;
    private javax.swing.JSpinner spnCenter;
    private javax.swing.JSpinner spnLeft;
    private javax.swing.JTextField txtMembershipName;
    // End of variables declaration//GEN-END:variables
}
