/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package dae.gui.components;

/**
 *
 * @author Koen Samyn
 */
public class NonCollapsibleHeader extends javax.swing.JPanel {

    /** Creates new form NonCollapsibleHeader */
    public NonCollapsibleHeader() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblTitle = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitle.setText("Title");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 8, 2, 0);
        add(lblTitle, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    public void setTitle(String title){
        lblTitle.setText(title);
    }
    
    public String getTitle(){
        return lblTitle.getText();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

}
