/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dae.prefabs.ui;

import dae.gui.EditFuzzySystemDialog;
import dae.prefabs.Prefab;
import dae.prefabs.parameters.Parameter;
import java.awt.Frame;
import mlproject.fuzzy.FuzzySystem;

/**
 *
 * @author Koen Samyn
 */
public class FuzzyParameterUI extends javax.swing.JPanel implements ParameterUI {

    private Parameter p;
    private Prefab currentPrefab;
    private static EditFuzzySystemDialog fuzzyDialog;

    /**
     * Creates new form FuzzyParameterUI
     */
    public FuzzyParameterUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLabel = new javax.swing.JLabel();
        txtFuzzySystemName = new javax.swing.JTextField();
        btnEditFuzzySystem = new javax.swing.JButton();

        lblLabel.setText("Property");

        txtFuzzySystemName.setEditable(false);

        btnEditFuzzySystem.setText("Edit ...");
        btnEditFuzzySystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditFuzzySystemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFuzzySystemName, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditFuzzySystem, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblLabel)
                .addComponent(txtFuzzySystemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnEditFuzzySystem))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditFuzzySystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditFuzzySystemActionPerformed
        // TODO add your handling code here:
        Object value = currentPrefab.getParameter(p.getId());
        if (value instanceof FuzzySystem) {
            FuzzySystem fs = (FuzzySystem) value;
            if (fuzzyDialog == null) {
                fuzzyDialog = new EditFuzzySystemDialog((Frame) this.getTopLevelAncestor(), true);
            }
            fuzzyDialog.setFuzzySystem(fs);
            fuzzyDialog.setVisible(true);
        }
    }//GEN-LAST:event_btnEditFuzzySystemActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditFuzzySystem;
    private javax.swing.JLabel lblLabel;
    private javax.swing.JTextField txtFuzzySystemName;
    // End of variables declaration//GEN-END:variables

    public void setParameter(Parameter p) {
        this.p = p;
        lblLabel.setText(p.getLabel());

    }

    public void setNode(Prefab currentSelectedNode) {
        currentPrefab = currentSelectedNode;
        Object value = currentPrefab.getParameter(p.getId());
        if (value instanceof FuzzySystem) {
            FuzzySystem fs = (FuzzySystem) value;
            txtFuzzySystemName.setText(fs.getName());
        }
    }
}
