package dae.prefabs.ui;

import dae.gui.EditFuzzySystemDialog;
import dae.prefabs.Prefab;
import dae.prefabs.ReflectionManager;
import dae.prefabs.parameters.Parameter;
import java.awt.Frame;
import mlproject.fuzzy.FuzzySystem;

/**
 *
 * @author Koen Samyn
 */
public class FuzzyParameterUI extends javax.swing.JPanel implements ParameterUI {

    private Parameter p;
    private Prefab currentPrefab;
    private static EditFuzzySystemDialog fuzzyDialog;

    /**
     * Creates new form FuzzyParameterUI
     */
    public FuzzyParameterUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        txtFuzzySystemName = new javax.swing.JTextField();
        btnEditFuzzySystem = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        txtFuzzySystemName.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        add(txtFuzzySystemName, gridBagConstraints);

        btnEditFuzzySystem.setText("Edit ...");
        btnEditFuzzySystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditFuzzySystemActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        add(btnEditFuzzySystem, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditFuzzySystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditFuzzySystemActionPerformed
        Object value = ReflectionManager.getInstance().invokeGetMethod(currentPrefab,this.p); 
        if (value instanceof FuzzySystem) {
            FuzzySystem fs = (FuzzySystem) value;
            if (fuzzyDialog == null) {
                fuzzyDialog = new EditFuzzySystemDialog((Frame) this.getTopLevelAncestor(), true);
            }
            fuzzyDialog.setFuzzySystem(fs);
            fuzzyDialog.setVisible(true);
        }
    }//GEN-LAST:event_btnEditFuzzySystemActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditFuzzySystem;
    private javax.swing.JTextField txtFuzzySystemName;
    // End of variables declaration//GEN-END:variables

    public void setParameter(Parameter p) {
        this.p = p;
    }
    
    public Parameter getParameter(){
        return p;
    }

    public void setNode(Prefab currentSelectedNode) {
        currentPrefab = currentSelectedNode;
        Object value = ReflectionManager.getInstance().invokeGetMethod(currentSelectedNode,p); 
        if (value instanceof FuzzySystem) {
            FuzzySystem fs = (FuzzySystem) value;
            txtFuzzySystemName.setText(fs.getName());
        }
    }
    
    /**
     * Checks if a label should be created for the UI.
     * @return true if a label should be created, false othwerise.
     */
    public boolean needsLabel(){
        return true;
    }
}
