/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dae.prefabs.ui;

import dae.GlobalObjects;
import dae.prefabs.Prefab;
import dae.prefabs.parameters.ParameterSection;
import java.awt.Component;
import java.awt.GridBagConstraints;
import java.util.HashMap;
import javax.swing.JComponent;
import javax.swing.border.TitledBorder;

/**
 *
 * @author Koen
 */
public class ParameterPanel extends javax.swing.JPanel {

    private ParameterSection parameterSection;
    private HashMap<String, ParameterUI> parameterUI =
            new HashMap<String, ParameterUI>();

    /**
     * Creates new form ParameterPanel
     */
    public ParameterPanel() {
        initComponents();
        GlobalObjects.getInstance().registerListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createTitledBorder("Parameter Section"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void setParameterSection(ParameterSection ps) {
        this.parameterSection = ps;
        ((TitledBorder) this.getBorder()).setTitle(parameterSection.getName());
    }

    public void addParameterUI(String id, ParameterUI pUI, GridBagConstraints gbc) {
        parameterUI.put(id, pUI);
        add((JComponent) pUI, gbc);
        revalidate();
    }

    public void setNode(Prefab currentSelectedNode) {
        for (Component c : this.getComponents()) {
            if (c instanceof ParameterUI) {
                ParameterUI pui = (ParameterUI) c;
                pui.setNode(currentSelectedNode);
            }
        }
    }
}