package dae.prefabs.ui;

import com.google.common.eventbus.Subscribe;
import dae.GlobalObjects;
import dae.components.ComponentType;
import dae.components.PrefabComponent;
import dae.prefabs.Prefab;
import dae.prefabs.events.ComponentListener;
import dae.prefabs.parameters.ParameterSection;
import dae.prefabs.types.ObjectType;
import dae.prefabs.types.ObjectTypeCategory;
import dae.prefabs.ui.events.SelectionEvent;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.awt.Rectangle;
import javax.swing.JLabel;
import javax.swing.Scrollable;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;

public class PrefabParameterPanel extends javax.swing.JPanel implements Scrollable, ComponentListener {

    private Prefab selected;
    private ObjectTypeCategory otCategories;
    private ObjectType currentObjectType;
    private JLabel filler = new JLabel();

    /**
     * Creates new form PrefabParameterPanel
     */
    public PrefabParameterPanel() {
        initComponents();
    }

    public void subscribeToPrefabSelectionEvent() {
        GlobalObjects.getInstance().registerListener(this);
    }

    public void createSelectedNodeUI() {
        if (selected == null) {
            return;
        }
        //System.out.println("Create selected ui");
        // find the correct definition for the type.
        if (otCategories == null) {
            otCategories = GlobalObjects.getInstance().getObjectsTypeCategory();
        }

        ObjectType ot = selected.getObjectType();

        //System.out.println("Found description : " + ot.getLabel());

        for (Component c : this.getComponents()) {
            this.remove(c);
        }
        currentObjectType = ot;
        this.invalidate();

        //System.out.println("Adding parameter sections");
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 0.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(3, 0, 3, 0);

        if (currentObjectType != null) {
            for (ParameterSection ps : currentObjectType.getParameterSections()) {
                ParameterPanel pp = ps.createParameterPanel();

                pp.setParameterSection(ps);
                pp.setNode(selected);
                this.add(pp, gbc);
                gbc.gridy++;
                pp.revalidate();
            }


            for (PrefabComponent c : selected.getComponents()) {
                ComponentType ct = otCategories.getComponent(c.getId());
              
                for (ParameterSection ps : ct.getParameterSections()) {
                    ParameterPanel pp = ps.createParameterPanel();

                    pp.setParameterSection(ps);
                    pp.setNode(selected);
                    this.add(pp, gbc);
                    gbc.gridy++;
                    pp.revalidate();
                }
            }
        }
        gbc.weighty = 1.0;
        this.add(filler, gbc);
        this.repaint();
    }

    public void setSelectedPrefab(Prefab prefab) {
        if (this.selected != prefab) {
            if (this.selected != null) {
                selected.removeComponentListener(this);
            }
            this.selected = prefab;
            selected.addComponentListener(this);
        }
    }

    @Subscribe
    public void prefabSelected(SelectionEvent selectionEvent) {
        //System.out.println("Prefab selected: " + selectionEvent.getSelectedNode().getName());
        if (this.selected != selectionEvent.getSelectedNode()) {
            if (this.selected != null) {
                selected.removeComponentListener(this);
            }
            this.selected = selectionEvent.getSelectedNode();
            selected.addComponentListener(this);
            SwingUtilities.invokeLater(new Runnable() {
                public void run() {
                    createSelectedNodeUI();
                }
            });
        }
    }

    public Dimension getPreferredScrollableViewportSize() {
        return getMinimumSize();
    }

    public int getScrollableUnitIncrement(Rectangle visibleRect, int orientation, int direction) {
        return 10;
    }

    public int getScrollableBlockIncrement(Rectangle visibleRect, int orientation, int direction) {
        return ((orientation == SwingConstants.VERTICAL) ? visibleRect.height : visibleRect.width) - 10;
    }

    public boolean getScrollableTracksViewportWidth() {
        return true;
    }

    public boolean getScrollableTracksViewportHeight() {
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(null);
        setLayout(new java.awt.GridBagLayout());
        add(jLabel1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public void componentAdded(Prefab prefab, PrefabComponent added) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                createSelectedNodeUI();
            }
        });
    }

    public void componentRemoved(Prefab prefab, PrefabComponent removed) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                createSelectedNodeUI();
            }
        });
    }
}
