package dae.prefabs.ui;

import java.awt.Component;
import java.awt.Container;
import java.awt.Insets;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.UIDefaults;

/**
 *
 * @author Koen Samyn
 */
public class PrefabComponentHeader extends javax.swing.JPanel {

    private boolean collapsed = false;
    private Icon arrowDown;
    private Icon arrowDownRollover;
    private Icon arrowRight;
    private Icon arrowRightRollover;

    /**
     * Creates new form PrefabComponentPanel
     */
    public PrefabComponentHeader() {
        initComponents();

        UIDefaults def = new UIDefaults();
        def.put("Button.contentMargins", new Insets(0, 0, 0, 0));
        btnCollapse.putClientProperty("Nimbus.Overrides", def);

    }

    public void setTitle(String title) {
        lblTitle.setText(title);
    }

    private Icon loadIcon(String path) {
        java.net.URL imgURL = getClass().getResource(path);
        if (imgURL != null) {
            ImageIcon icon = new ImageIcon(imgURL);
            icon.setImageObserver(this);
            return icon;
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnCollapse = new javax.swing.JButton();
        lblIcon = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblComponentMenu = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        btnCollapse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dae/icons/bullet_arrow_down.png"))); // NOI18N
        btnCollapse.setContentAreaFilled(false);
        btnCollapse.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnCollapse.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/dae/icons/bullet_arrow_down_rollover.png"))); // NOI18N
        btnCollapse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCollapseActionPerformed(evt);
            }
        });
        add(btnCollapse, new java.awt.GridBagConstraints());

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dae/icons/page_gear.png"))); // NOI18N
        add(lblIcon, new java.awt.GridBagConstraints());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitle.setText("Title");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        add(lblTitle, gridBagConstraints);

        lblComponentMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dae/icons/cog.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        add(lblComponentMenu, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCollapseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCollapseActionPerformed
        if (getParent() != null) {
            Container pp = (Container) getParent();
            for (Component c : pp.getComponents()) {
                if (c != this ) {
                    c.setVisible(collapsed);
                }
            }
            collapsed = !collapsed;

            if (collapsed) {
                if (arrowRight == null && arrowRightRollover == null) {

                    arrowRight = loadIcon("/dae/icons/bullet_arrow_right.png");
                    arrowRightRollover = loadIcon("/dae/icons/bullet_arrow_right_rollover.png");
                }

                btnCollapse.setIcon(arrowRight);
                btnCollapse.setRolloverIcon(arrowRightRollover);
            } else {
                if (arrowDown == null && arrowDownRollover == null) {
                    arrowDown = loadIcon("/dae/icons/bullet_arrow_down.png");
                    arrowDownRollover = loadIcon("/dae/icons/bullet_arrow_down_rollover.png");
                }
                btnCollapse.setIcon(arrowDown);
                btnCollapse.setRolloverIcon(arrowDownRollover);
            }
        }
    }//GEN-LAST:event_btnCollapseActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCollapse;
    private javax.swing.JLabel lblComponentMenu;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
