package dae.prefabs.ui;

import com.google.common.eventbus.Subscribe;
import dae.GlobalObjects;
import dae.prefabs.ui.events.LayerEvent;
import dae.prefabs.ui.events.LayerEvent.LayerEventType;
import dae.prefabs.ui.events.LevelEvent;
import dae.prefabs.ui.events.LevelEvent.EventType;
import dae.prefabs.ui.events.ProjectEvent;
import dae.prefabs.ui.events.ProjectEventType;
import dae.prefabs.ui.events.SelectionEvent;
import java.awt.CardLayout;
import javax.swing.SwingUtilities;

/**
 *
 * @author Koen Samyn
 */
public class PropertiesPanel extends javax.swing.JPanel {

    /**
     * Creates new form PropertiesPanel
     */
    public PropertiesPanel() {
        initComponents();
        GlobalObjects.getInstance().registerListener(this);
    }

    @Subscribe
    public void prefabSelected(SelectionEvent selectionEvent) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                CardLayout cl = (CardLayout) getLayout();
                cl.show(PropertiesPanel.this, "Prefab");
            }
        });
    }

    @Subscribe
    public void projectSelected(final ProjectEvent event) {
        if ( event.getEventType() == ProjectEventType.SELECTED)
        {
        SwingUtilities.invokeLater(new Runnable() {
                public void run() {
                    CardLayout cl = (CardLayout) getLayout();
                    cl.show(PropertiesPanel.this, "Project");
                }
            });
        }
    }

    @Subscribe
    public void levelSelected(final LevelEvent event) {
        if (event.getEventType() == EventType.LEVELSELECTED) {
            SwingUtilities.invokeLater(new Runnable() {
                public void run() {
                    CardLayout cl = (CardLayout) getLayout();
                    cl.show(PropertiesPanel.this, "Level");
                }
            });
        }
    }

    @Subscribe
    public void layerSelected(final LayerEvent event) {
        if (event.getEventType() == LayerEventType.SELECTED) {
            SwingUtilities.invokeLater(new Runnable() {
                public void run() {
                    CardLayout cl = (CardLayout) getLayout();
                    cl.show(PropertiesPanel.this, "Layer");
                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prefabParameterPanel1 = new dae.prefabs.ui.PrefabParameterPanel();
        layerPropertiesPanel1 = new dae.prefabs.ui.LayerPropertiesPanel();
        projectParameterPanel1 = new dae.prefabs.ui.ProjectParameterPanel();
        levelParameterPanel1 = new dae.gui.level.LevelParameterPanel();

        setLayout(new java.awt.CardLayout());
        add(prefabParameterPanel1, "Prefab");
        add(layerPropertiesPanel1, "Layer");
        add(projectParameterPanel1, "Project");
        add(levelParameterPanel1, "Level");
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private dae.prefabs.ui.LayerPropertiesPanel layerPropertiesPanel1;
    private dae.gui.level.LevelParameterPanel levelParameterPanel1;
    private dae.prefabs.ui.PrefabParameterPanel prefabParameterPanel1;
    private dae.prefabs.ui.ProjectParameterPanel projectParameterPanel1;
    // End of variables declaration//GEN-END:variables
}
