/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dae.prefabs.ui;

import dae.prefabs.Prefab;
import dae.prefabs.parameters.Parameter;
import dae.prefabs.parameters.RangeParameter;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author samyn_000
 */
public class RangeParameterUI extends javax.swing.JPanel implements ParameterUI, ChangeListener {

    private Parameter p;
    private Prefab currentPrefab;

    /**
     * Creates new form RangeParameterUI
     */
    public RangeParameterUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblPropertyName = new javax.swing.JLabel();
        spnValue = new javax.swing.JSpinner();

        setLayout(new java.awt.GridBagLayout());

        lblPropertyName.setText("Label :");
        lblPropertyName.setPreferredSize(new java.awt.Dimension(100, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(lblPropertyName, gridBagConstraints);

        spnValue.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(1.0d)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        add(spnValue, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblPropertyName;
    private javax.swing.JSpinner spnValue;
    // End of variables declaration//GEN-END:variables

    public void setParameter(Parameter p) {
        this.p = p;
        lblPropertyName.setText(p.getId());
        RangeParameter rp = (RangeParameter) p;
        SpinnerNumberModel model1 = new SpinnerNumberModel(rp.getDefaultValue(), rp.getMin(), rp.getMax(), rp.getStep()); 
        
        spnValue.setModel(model1);
    }
    
    public void setLabel(String label) {
        lblPropertyName.setText(label);
    }
    
    public void setNode(Prefab currentSelectedNode) {
        spnValue.removeChangeListener(this);
        this.currentPrefab = currentSelectedNode;
        Object value = currentSelectedNode.getParameter(p.getId());
        this.spnValue.setValue(value);
        spnValue.addChangeListener(this);
    }
    
    public void stateChanged(ChangeEvent e) {
        Double d = (Double)spnValue.getValue();        
        currentPrefab.setParameter(p.getId(), d.floatValue(), true);
    }
}
