/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dae.prefabs.ui;

import dae.prefabs.Prefab;
import dae.prefabs.parameters.Parameter;
import dae.prefabs.standard.UpdateObject;

/**
 *
 * @author Koen
 */
public class TextParameterUI extends javax.swing.JPanel implements ParameterUI {

    private Parameter parameter;
    private boolean disregardEvent;
    private Prefab currentNode;

    /**
     * Creates new form TextParameterUI
     */
    public TextParameterUI() {
        initComponents();
    }

    @Override
    public void setParameter(Parameter p) {
        this.parameter = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        lblLabel = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setLayout(new java.awt.GridBagLayout());

        lblLabel.setText("Label : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 3, 0);
        add(lblLabel, gridBagConstraints);

        txtMessage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMessageKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 3, 5);
        add(txtMessage, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMessageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMessageKeyTyped
        // TODO add your handling code here:
        if ( !disregardEvent )
        {
            currentNode.setParameter(parameter.getId(), txtMessage.getText(), true);
        }
    }//GEN-LAST:event_txtMessageKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLabel;
    private javax.swing.JTextField txtMessage;
    // End of variables declaration//GEN-END:variables

    public void setLabel(String id) {
        lblLabel.setText(id);
    }

    @Override
    public void setNode(Prefab currentSelectedNode) {
        currentNode = currentSelectedNode;
        String property = parameter.getId();
        Object value = currentSelectedNode.getParameter(property);
        if (value != null) {
            disregardEvent = true;
            txtMessage.setText(currentSelectedNode.getParameter(property).toString());
            disregardEvent = false;
        }
    }
}
