/*
 * Digital Arts and Entertainment 
 */
package dae.animation.rig.timing.gui;

import dae.animation.rig.Rig;
import dae.animation.rig.timing.Behaviour;
import dae.prefabs.Prefab;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.Document;

/**
 *
 * @author Koen.Samyn
 */
public class BehaviourSelectorPanel extends javax.swing.JPanel {

    private Rig model;
    private DefaultComboBoxModel<Behaviour> cboModel;

    /**
     * Creates new form BehaviourSelector
     */
    public BehaviourSelectorPanel() {
        initComponents();
        Document d = txtBehaviourName.getDocument();
        d.addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                checkBehaviourName();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                checkBehaviourName();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                checkBehaviourName();
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        cboBehaviours = new javax.swing.JComboBox<>();
        lblNumberOfFrames = new javax.swing.JLabel();
        lblFPS = new javax.swing.JLabel();
        spnFrameNumbers = new javax.swing.JSpinner();
        spnFPS = new javax.swing.JSpinner();
        lblNewBehaviour = new javax.swing.JLabel();
        txtBehaviourName = new dae.gui.components.AlphaNumericTextField();
        btnAddBehaviour = new javax.swing.JButton();
        separator = new javax.swing.JSeparator();

        jTextField1.setText("jTextField1");

        cboBehaviours.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboBehavioursItemStateChanged(evt);
            }
        });

        lblNumberOfFrames.setText("# Frames : ");

        lblFPS.setText("FPS :");

        lblNewBehaviour.setText("New behaviour");

        btnAddBehaviour.setText("Add");
        btnAddBehaviour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBehaviourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separator)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNumberOfFrames)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnFrameNumbers))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFPS)
                        .addGap(43, 43, 43)
                        .addComponent(spnFPS))
                    .addComponent(cboBehaviours, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNewBehaviour)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBehaviourName, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddBehaviour)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboBehaviours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnFPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFPS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnFrameNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumberOfFrames))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewBehaviour)
                    .addComponent(txtBehaviourName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddBehaviour))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddBehaviourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBehaviourActionPerformed
        String name = txtBehaviourName.getText();
        Behaviour b = new Behaviour(name, model.getDefaultFPS());
        txtBehaviourName.setText("");
        model.addBehaviour(b);
        cboModel.addElement(b);
        selectBehaviour(b);
    }//GEN-LAST:event_btnAddBehaviourActionPerformed

    private void cboBehavioursItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboBehavioursItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            Behaviour selected = (Behaviour) evt.getItem();
            selectBehaviour(selected);
            model.setCurrentBehaviour(selected);
        }
    }//GEN-LAST:event_cboBehavioursItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBehaviour;
    private javax.swing.JComboBox<Behaviour> cboBehaviours;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblFPS;
    private javax.swing.JLabel lblNewBehaviour;
    private javax.swing.JLabel lblNumberOfFrames;
    private javax.swing.JSeparator separator;
    private javax.swing.JSpinner spnFPS;
    private javax.swing.JSpinner spnFrameNumbers;
    private dae.gui.components.AlphaNumericTextField txtBehaviourName;
    // End of variables declaration//GEN-END:variables

    private void checkBehaviourName() {
        String name = txtBehaviourName.getText();
        if (name.length() == 0 || model == null) {
            btnAddBehaviour.setEnabled(false);
            return;
        }
        if (model != null) {
            btnAddBehaviour.setEnabled(!model.containsBehaviour(name));
        }
    }

    public void setPrefab(Prefab prefab) {
        txtBehaviourName.setText("");
        if (prefab instanceof Rig) {
            model = (Rig) prefab;
            cboModel = new DefaultComboBoxModel(model.getBehaviours().toArray());
            cboBehaviours.setModel(cboModel);
        }
    }

    private void selectBehaviour(Behaviour b) {
        cboBehaviours.setSelectedItem(b);
        spnFPS.setValue(b.getFPS());
    }

    public void addBehaviourListener(ItemListener il) {
        cboBehaviours.addItemListener(il);
    }
}
