/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dae.animation.rig.gui;

import dae.animation.rig.AnimationController;
import dae.animation.rig.Rig;
import javax.swing.DefaultComboBoxModel;
import mlproject.fuzzy.FuzzySystem;
import mlproject.fuzzy.FuzzyVariable;

/**
 *
 * @author Koen Samyn
 */
public class ControllerConnector extends javax.swing.JPanel {

    private Rig rig;
    private AnimationController animationController;

    /**
     * Creates new form ControllerConnector
     */
    public ControllerConnector() {
        initComponents();
    }

    public void setRig(Rig rig) {
        this.rig = rig;

        FuzzySystem system = rig.getFuzzySystem();
        int nrOfInputs = system.getNrOfInputs();
        FuzzyVariable[] inputs = new FuzzyVariable[nrOfInputs];
        for (int i = 0; i < nrOfInputs; ++i) {
            inputs[i] = system.getFuzzyInputAt(i);
        }
        cboInputVariables.setModel(new DefaultComboBoxModel(inputs));
        int nrOfOutputs = system.getNrOfOutputs();
        FuzzyVariable[] outputs = new FuzzyVariable[nrOfOutputs];
        for (int i = 0; i < nrOfOutputs; ++i) {
            outputs[i] = system.getFuzzyOutputAt(i);
        }
        cboOutputVariables.setModel(new DefaultComboBoxModel(outputs));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        txtControllerName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cboInputVariables = new javax.swing.JComboBox();
        lblOutput = new javax.swing.JLabel();
        cboOutputVariables = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Controller connector"));
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Controller name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 2, 0);
        add(jLabel1, gridBagConstraints);

        txtControllerName.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 2, 5);
        add(txtControllerName, gridBagConstraints);

        jLabel2.setText("Input :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jLabel2, gridBagConstraints);

        cboInputVariables.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboInputVariables.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboInputVariablesItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 5);
        add(cboInputVariables, gridBagConstraints);

        lblOutput.setText("Output :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(lblOutput, gridBagConstraints);

        cboOutputVariables.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboOutputVariables.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboOutputVariablesItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 5);
        add(cboOutputVariables, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weighty = 1.0;
        add(jLabel3, gridBagConstraints);

        jLabel4.setText("<html>Use this panel to connect the input to the <b>input variable</b> of the controller, and the output to the <b>output</b> variable of the controller.</html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 2, 0);
        add(jLabel4, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void cboInputVariablesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboInputVariablesItemStateChanged
        FuzzyVariable selected = (FuzzyVariable) evt.getItem();
        if (animationController != null) {
            animationController.setControllerInputName(selected.getName());
        }
    }//GEN-LAST:event_cboInputVariablesItemStateChanged

    private void cboOutputVariablesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboOutputVariablesItemStateChanged
        FuzzyVariable selected = (FuzzyVariable) evt.getItem();
        if (animationController != null) {
            animationController.setControllerOutputName(selected.getName());
        }
    }//GEN-LAST:event_cboOutputVariablesItemStateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboInputVariables;
    private javax.swing.JComboBox cboOutputVariables;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JTextField txtControllerName;
    // End of variables declaration//GEN-END:variables

    void setAnimationController(AnimationController ac) {
        animationController = ac;
        if (animationController != null) {
            if (ac.getControllerInputName() == null) {
                FuzzyVariable selected = (FuzzyVariable) cboInputVariables.getSelectedItem();
                animationController.setControllerInputName(selected.getName());
            } else {
                FuzzyVariable input = rig.getFuzzySystem().getFuzzyInputVariable(ac.getControllerInputName());
                cboInputVariables.setSelectedItem(input);
            }
            if (ac.getControllerOutputName() == null) {
                FuzzyVariable selected = (FuzzyVariable) cboOutputVariables.getSelectedItem();
                animationController.setControllerOutputName(selected.getName());
            } else {
                FuzzyVariable output = rig.getFuzzySystem().getFuzzyOutputVariable(ac.getControllerOutputName());
                cboOutputVariables.setSelectedItem(output);
            }
        }
    }
}
